# Notebook for testing around

## testing condition of matrix

In [1]:
from numpy import linalg as LA
from block_matrix import BlockMatrix

In [7]:
A = BlockMatrix(1,4).get_sparse().toarray()
print(A)
print(LA.cond(A))

A = BlockMatrix(1,10).get_sparse().toarray()
print(A)
print(LA.cond(A))

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]
5.8284271247461925
[[ 2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2.]]
39.86345818906128


In [8]:
A = BlockMatrix(2,4).get_sparse().toarray()
print(A)
print(LA.cond(A))

A = BlockMatrix(2,10).get_sparse().toarray()
print(A)
print(LA.cond(A))

[[ 4. -1.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  4.  0.  0. -1.  0.  0.  0.]
 [-1.  0.  0.  4. -1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  4. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.  4.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.  0.  4. -1.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  4. -1.]
 [ 0.  0.  0.  0.  0. -1.  0. -1.  4.]]
5.828427124746192
[[ 4. -1.  0. ...  0.  0.  0.]
 [-1.  4. -1. ...  0.  0.  0.]
 [ 0. -1.  4. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  4. -1.  0.]
 [ 0.  0.  0. ... -1.  4. -1.]
 [ 0.  0.  0. ...  0. -1.  4.]]
39.86345818906138


## testing ...